// Country name (as stored on the user's profile) -> primary IANA timezone.
// Used to format scan timestamps in the owner's chosen country instead of
// whatever timezone their current device/browser happens to be set to.
export const COUNTRY_TIMEZONES: Record<string, string> = {
  Afghanistan: 'Asia/Kabul',
  Albania: 'Europe/Tirane',
  Algeria: 'Africa/Algiers',
  Argentina: 'America/Argentina/Buenos_Aires',
  Armenia: 'Asia/Yerevan',
  Australia: 'Australia/Sydney',
  Austria: 'Europe/Vienna',
  Azerbaijan: 'Asia/Baku',
  Bahrain: 'Asia/Bahrain',
  Bangladesh: 'Asia/Dhaka',
  Belarus: 'Europe/Minsk',
  Belgium: 'Europe/Brussels',
  Bhutan: 'Asia/Thimphu',
  Bolivia: 'America/La_Paz',
  Brazil: 'America/Sao_Paulo',
  Bulgaria: 'Europe/Sofia',
  Cambodia: 'Asia/Phnom_Penh',
  Cameroon: 'Africa/Douala',
  Canada: 'America/Toronto',
  Chile: 'America/Santiago',
  China: 'Asia/Shanghai',
  Colombia: 'America/Bogota',
  'Costa Rica': 'America/Costa_Rica',
  Croatia: 'Europe/Zagreb',
  Cuba: 'America/Havana',
  Cyprus: 'Asia/Nicosia',
  'Czech Republic': 'Europe/Prague',
  Denmark: 'Europe/Copenhagen',
  Ecuador: 'America/Guayaquil',
  Egypt: 'Africa/Cairo',
  Estonia: 'Europe/Tallinn',
  Ethiopia: 'Africa/Addis_Ababa',
  Finland: 'Europe/Helsinki',
  France: 'Europe/Paris',
  Georgia: 'Asia/Tbilisi',
  Germany: 'Europe/Berlin',
  Ghana: 'Africa/Accra',
  Greece: 'Europe/Athens',
  'Hong Kong S.A.R.': 'Asia/Hong_Kong',
  Hungary: 'Europe/Budapest',
  Iceland: 'Atlantic/Reykjavik',
  India: 'Asia/Kolkata',
  Indonesia: 'Asia/Jakarta',
  Iran: 'Asia/Tehran',
  Iraq: 'Asia/Baghdad',
  Ireland: 'Europe/Dublin',
  Israel: 'Asia/Jerusalem',
  Italy: 'Europe/Rome',
  Jamaica: 'America/Jamaica',
  Japan: 'Asia/Tokyo',
  Jordan: 'Asia/Amman',
  Kazakhstan: 'Asia/Almaty',
  Kenya: 'Africa/Nairobi',
  'South Korea': 'Asia/Seoul',
  Kuwait: 'Asia/Kuwait',
  Kyrgyzstan: 'Asia/Bishkek',
  Laos: 'Asia/Vientiane',
  Latvia: 'Europe/Riga',
  Lebanon: 'Asia/Beirut',
  Libya: 'Africa/Tripoli',
  Lithuania: 'Europe/Vilnius',
  Luxembourg: 'Europe/Luxembourg',
  'Macau S.A.R.': 'Asia/Macau',
  Malaysia: 'Asia/Kuala_Lumpur',
  Maldives: 'Indian/Maldives',
  Malta: 'Europe/Malta',
  Mauritius: 'Indian/Mauritius',
  Mexico: 'America/Mexico_City',
  Moldova: 'Europe/Chisinau',
  Mongolia: 'Asia/Ulaanbaatar',
  Morocco: 'Africa/Casablanca',
  Myanmar: 'Asia/Yangon',
  Namibia: 'Africa/Windhoek',
  Nepal: 'Asia/Kathmandu',
  Netherlands: 'Europe/Amsterdam',
  'New Zealand': 'Pacific/Auckland',
  Nigeria: 'Africa/Lagos',
  Norway: 'Europe/Oslo',
  Oman: 'Asia/Muscat',
  Pakistan: 'Asia/Karachi',
  Panama: 'America/Panama',
  Paraguay: 'America/Asuncion',
  Peru: 'America/Lima',
  Philippines: 'Asia/Manila',
  Poland: 'Europe/Warsaw',
  Portugal: 'Europe/Lisbon',
  Qatar: 'Asia/Qatar',
  Romania: 'Europe/Bucharest',
  Russia: 'Europe/Moscow',
  'Saudi Arabia': 'Asia/Riyadh',
  Serbia: 'Europe/Belgrade',
  Singapore: 'Asia/Singapore',
  Slovakia: 'Europe/Bratislava',
  Slovenia: 'Europe/Ljubljana',
  'South Africa': 'Africa/Johannesburg',
  Spain: 'Europe/Madrid',
  'Sri Lanka': 'Asia/Colombo',
  Sweden: 'Europe/Stockholm',
  Switzerland: 'Europe/Zurich',
  Taiwan: 'Asia/Taipei',
  Tajikistan: 'Asia/Dushanbe',
  Tanzania: 'Africa/Dar_es_Salaam',
  Thailand: 'Asia/Bangkok',
  Tunisia: 'Africa/Tunis',
  Turkey: 'Europe/Istanbul',
  Turkmenistan: 'Asia/Ashgabat',
  Uganda: 'Africa/Kampala',
  Ukraine: 'Europe/Kiev',
  'United Arab Emirates': 'Asia/Dubai',
  'United Kingdom': 'Europe/London',
  'United States': 'America/New_York',
  Uruguay: 'America/Montevideo',
  Uzbekistan: 'Asia/Samarkand',
  Venezuela: 'America/Caracas',
  Vietnam: 'Asia/Ho_Chi_Minh',
  Yemen: 'Asia/Aden',
  Zambia: 'Africa/Lusaka',
  Zimbabwe: 'Africa/Harare',
};

export function getTimezoneForCountry(country: string | null | undefined): string | undefined {
  if (!country) return undefined;
  return COUNTRY_TIMEZONES[country];
}
